version: '3.8'

services:
  middleware:
    build:
      context: .
    container_name: middleware
    privileged: true
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app

networks:
  default:
    name: ranger-env
    external: true
