version: '3.8'

services:
  middleware:
    build:
      context: .
    container_name: middleware
    privileged: true
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app

networks:
  default:
    name: blockchain-env
    external: true
