# Imagen base
FROM node:16

# Instalar herramientas CLI necesarias
RUN apt-get update && apt-get install docker.io -y \
    bash \
    curl

# Directorio de trabajo
WORKDIR /app

# Copiar el código del middleware
COPY package.json package-lock.json ./
RUN npm install
COPY . .

# Exponer el puerto
EXPOSE 3000

# Comando de inicio
CMD ["node", "middleware.js"]
